create table if not exists public.app_logs (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid(),
  level text not null,
  message text not null,
  metadata jsonb not null default '{}',
  created_at timestamptz default now()
);

alter table public.app_logs
add column if not exists user_id uuid default auth.uid();

create index if not exists app_logs_user_created_at_idx
on public.app_logs (user_id, created_at desc);

alter table public.app_logs enable row level security;

create policy "Users can read their own app logs"
on public.app_logs
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert their own app logs"
on public.app_logs
for insert
to authenticated
with check ((select auth.uid()) = user_id);

grant select, insert on table public.app_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;
